import pkgutil
import os

# נתיב לקובץ ה-.gitignore
gitignore_path = '.gitignore'

# קבל את רשימת המודולים המותקנים
installed_modules = {module.name for module in pkgutil.iter_modules()}

# תבניות להוספה ל-.gitignore
patterns = [
    "*.pyc",
    "__pycache__/",
    "*.pyo",
    "*.pyd",
    "*.pdb",
    "*.egg-info/",
    "build/",
    "dist/",
    "*.egg",
    "*.whl",
    "*.dll",
    "*.so",
    "*.dylib",
    "*.log",
    "*.tmp",
    "*.temp",
    "*.swp",
    "*.sqlite3",
    ".venv/",
    "venv/",
    ".env/",
    ".vscode/",
    ".idea/",
    ".pytest_cache/",
    ".mypy_cache/",
    ".hypothesis/",
    ".ipynb_checkpoints/",
]

# הוסף את שמות המודולים המותקנים לתבניות
patterns.extend(installed_modules)

# כתוב את התבניות לקובץ .gitignore
with open(gitignore_path, 'a') as f:
    f.write('\n# Auto-generated by script\n')
    for pattern in patterns:
        f.write(pattern + '\n')

print(f".gitignore file updated with installed modules and common patterns.")
